### ISSUE TITLE
Little lag when switching from vim to tmux pane

### ISSUE THREAD

**Issue by nozim** [christoomey/vim-tmux-navigator#114] opened 2016-03-31 08:30 UTC
When I'm in vim pane and switch to tmux it takes little more time than switching between tmux panes or from tmux -> vim. 

I'm using MacVim 7.4 and tmux 2.0.

**Comment by christoomey** [comment] 2016-04-01 18:03
Hey @nozim, my guess is that you have additional mappings in Vim, something like `<C-h>a`, so Vim waits after receiving `<C-h>` to see if you're going to type an `a`.

To check, you can run the command `:verbose nmap <C-h>` to check. It will list out all normal mode mappings that start with `<C-h>`.

**Comment by nozim** [comment] 2016-04-08 08:51
Hi @christoomey, I've checked the mappings, no any other mappings found, but thanks for hint :)

**Comment by bradens** [comment] 2016-06-09 18:24
Experiencing the same thing, also have no other mappings than the ones from tmux-navigator

**Comment by blueyed** [comment] 2016-06-09 20:14
@bradens 
Are you using master by now (with a new method)?

It is expected to take a bit longer, since it goes through the Vim plugin in that case - but it should not be really noticeable.

Does it affect all directions?
Check e.g. `:map <c-h>` in Vim, if there's nothing like `<c-h>w` in there.

You could try adding a `debug` in front of the Vim command in the mapping and see if something in there looks fishy when stepping through it.

**Comment by bradens** [comment] 2016-06-10 17:55
@blueyed Yea, i'm using master now. 

I looked at the source and noticed basically it all boils down to a `system('tmux -S <socket_name> "select-pane <direction>"')`  And i tried just running that command from vim and still noticed the lag.  It's probably not something vim-tmux-navigator can fix 😢

**Comment by blueyed** [comment] 2016-06-10 17:58
@bradens 
Do you use Windows?

**Comment by bradens** [comment] 2016-06-10 18:00
No, sorry I forgot to mention.  I'm using Mac OS 10.11.1 with neovim v0.1.2-358-g130611f, tmux 2.1

**Comment by blueyed** [comment] 2016-06-10 22:42
Strange then.. I've thought that it might be related to Windows being not fast with subprocesses.

How long is the delay?  More than a second?

**Comment by bradens** [comment] 2016-06-12 22:19
The delay is just above the tolerable amount :(. About 1 second

**Comment by blueyed** [comment] 2016-06-17 18:51
This should make it ~50% faster: https://github.com/christoomey/vim-tmux-navigator/pull/134 - eliminating one of two `system` calls.

Check out Vim's `profile` feature, which you can use additionally: use a function like https://github.com/blueyed/dotfiles/blob/master/vimrc#L6-L26, then trigger the slow thing a few times and call `:profile stop`.
Profiling information will be written to the file.

It's how I found out about the unnecessary `system` call for tmate-detection.

**Comment by bradens** [comment] 2016-07-15 17:39
@blueyed Sorry for not getting back to you sooner.  Your fix works great, it's now ~ 500ms to switch, which is much better.

**Comment by christoomey** [comment] 2016-07-15 20:28
Sounds like @blueyed has found the root cause and https://github.com/christoomey/vim-tmux-navigator/pull/134 is in works to merge solution. I'm going to close this now and we can track via #134, but please feel free to comment or reopen if I missed anything.

**Closed by christoomey** 2016-07-15 20:28 UTC
