### ISSUE TITLE
can I use this plugin in git bash on Windows system?

### ISSUE THREAD

**Issue by CengsBlanky** [christoomey/vim-tmux-navigator#322] opened 2022-10-11 12:00 UTC
I typed vim command :TmuxNavigatorProcessList. The output of that command is `ps -o state= -o comm= -t /dev/pty3' returned 1`, I think git bash is different from other unix-like system environment, so the command is not working as it should be. Is there any work around method to detect vim?

**Comment by christoomey** [comment] 2022-10-11 13:10
Unfortunately my guess is that this will not work in git bash. You could try [Mislav’s script](https://github.com/mislav/dotfiles/blob/master/bin/tmux-vim-select-pane) or wrapper versions of the vim detection tmux commands (https://github.com/christoomey/vim-tmux-navigator/tree/c33a8a97028cac38040f1b8d9292337104026ad6#tmux), but I wouldn’t be surprised if it didn’t work as intended unfortunately due to the differences between git bash.

For whatever it’s worth, back when I was on windows I used Cygwin for unixy things (after trying git bash and finding it lacking), and I hear great things about Windows Subsystem for Linux these days.

I’m going to close this now, but hopefully those notes help!

**Closed by christoomey** 2022-10-11 13:10 UTC
