### ISSUE TITLE
Backspace won't work in tmux

### ISSUE THREAD

**Issue by lowe0292** [christoomey/vim-tmux-navigator#59] opened 2015-01-15 18:59 UTC
I use this setup extensively, but recently my backspace key stopped working in tmux. Now, backspace jumps between vertically split windows. Here's my .tmux.conf:

```
bind -n C-k run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U" 
bind -n C-j run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D" 
bind -n C-h run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L" 
bind -n C-l run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R" 

set -g prefix C-a # this just changes my prefix from ctrl-b to ctrl-a
bind \ split-window -h # Split panes horizontal
bind - split-window -v # Split panes vertically  
```

If I remove the left and right bindings (C-h and C-l), then backspace starts working again. Any ideas?

**Comment by christoomey** [comment] 2015-01-15 19:08
Hello @lowe0292, haven't seen this myself, but hopefully we can figure it out. My guess is that a terminal setting changed and now your delete (backspace?) key is set to send `^h`. Can you check your terminal settings?

**Comment by abair** [comment] 2015-09-30 05:41
Hi @lowe0292, I expect @christoomey is correct about the cause of your issue.  My terminal does not send `^h` for backspace, but I often type it in manually when it's more convenient to do so.  Because of this (and having to move `^l` to `<prefix>^l`), I find this amazing plugin to be unusable for me, since I can't come up with any better control keys that don't overlap already useful ones :'(

Since I'm already used to split switching in vim with `<c-w>w`, `<c-w>h`, etc, I've set up some tmux files and my vimrc to make tmuxnavigator behave like vim :D  It doesn't seem appropriate for a pull request, but this could be a good place to put it:

##### .vimrc
```vim
" tmux navigator stuff
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-w>h :TmuxNavigateLeft<cr>
nnoremap <silent> <c-w>j :TmuxNavigateDown<cr>
nnoremap <silent> <c-w>k :TmuxNavigateUp<cr>
nnoremap <silent> <c-w>l :TmuxNavigateRight<cr>
nnoremap <silent> <c-w>; :TmuxNavigatePrevious<cr>
```

##### .tmux.config
```sh
# Smart pane switching with awareness of vim splits that acts like VIM's C-w
bind -n C-w source-file ~/.tmux/tmuxnavigate_mode
bind C-w send-keys C-w # pass C-w to the program
```

##### .tmux/tmuxnavigator_mode
```sh
# Smart pane switching with awareness of vim splits.  Acts like C-w in vim
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'

bind -n h if-shell "$is_vim" "send-keys C-w 'h'" "select-pane -L"\; source ~/.tmux/tmuxnavigate_esc
bind -n j if-shell "$is_vim" "send-keys C-w 'j'" "select-pane -D"\; source ~/.tmux/tmuxnavigate_esc
bind -n k if-shell "$is_vim" "send-keys C-w 'k'" "select-pane -U"\; source ~/.tmux/tmuxnavigate_esc
bind -n l if-shell "$is_vim" "send-keys C-w 'l'" "select-pane -R"\; source ~/.tmux/tmuxnavigate_esc
bind -n w if-shell "$is_vim" "send-keys C-w 'w'" "select-pane -t :.+"\; source ~/.tmux/tmuxnavigate_esc
bind -n \; if-shell "$is_vim" "send-keys C-w ';;'" "select-pane -l"\; source ~/.tmux/tmuxnavigate_esc

bind -n C-h if-shell "$is_vim" "send-keys C-w 'h'" "select-pane -L"\; source ~/.tmux/tmuxnavigate_esc
bind -n C-j if-shell "$is_vim" "send-keys C-w 'j'" "select-pane -D"\; source ~/.tmux/tmuxnavigate_esc
bind -n C-k if-shell "$is_vim" "send-keys C-w 'k'" "select-pane -U"\; source ~/.tmux/tmuxnavigate_esc
bind -n C-l if-shell "$is_vim" "send-keys C-w 'l'" "select-pane -R"\; source ~/.tmux/tmuxnavigate_esc
bind -n C-w if-shell "$is_vim" "send-keys C-w 'w'" "select-pane -t :.+"\; source ~/.tmux/tmuxnavigate_esc
bind -n C-\; if-shell "$is_vim" "send-keys C-w ';;'" "select-pane -l"\; source ~/.tmux/tmuxnavigate_esc
```

##### .tmux/tmuxnavigator_esc
```sh
# unbind the tmuxnaviage keys, like hitting esc from within "tmuxnavigate mode"
unbind -n h
unbind -n j
unbind -n k
unbind -n l
unbind -n w
unbind -n \;

unbind -n C-h
unbind -n C-j
unbind -n C-k
unbind -n C-l
unbind -n C-w
unbind -n C-\;

bind -n C-w source-file ~/.tmux/tmuxnavigate_mode
```

Since `C-w` is now caught by tmux, `bind C-w send-keys C-w` is used to pass `C-w` to the application for stuff like moving panes in vim (`<ctrl-w>H`).

There's no timeout on the `C-w` key, which is annoying side effect of doing it this way.

**Comment by roxma** [comment] 2016-06-14 09:48
I map the keys to `^s` `^f` `^d` `^e`, as many games use `E` `S` `D` `F` as movement keys.
seems only `^f` overlap vim's page down key, in most case I don't need it, so It's ok then.

**Comment by christoomey** [comment] 2017-12-31 13:07
Hi @lowe0292, been a while since we've heard anything on this issue, so I'm going to close it, but please feel free to comment or re-open should you still have an issue.

**Closed by christoomey** 2017-12-31 13:07 UTC

**Comment by a-schaefers** [comment] 2018-01-10 02:18
Hello, I have this exact problem in the new alacritty terminal, as soon as I disable vim-tmux-navigator plugin and restart tmux, the backspace (and delete key) will work again. This does not affect urxvt.

**Comment by peiyuanzheng** [comment] 2018-01-10 09:02
I have this same problem in ITerm.  Solution: In iTerm preferences->keys, change 'delete' sent to '^?' .  Also check the setting in preferences->profiles->keys.

**Comment by christoomey** [comment] 2018-01-10 15:12
While this plugin does bring out this issue, I don't believe it is actually the cause of the problem. The source of the issue is that the plugin in mapping `C-h` (aka `^h`) which some terminals will be configured to interpret as backspace. I don't believe there is anything we can do in the plugin, but there should be a setting that you can use to fix this behavior.

**Comment by xanoni** [comment] 2021-08-12 05:52
https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95

this solved it for me

**Comment by Asocia** [comment] 2022-03-05 13:43
Well, it is not some terminals interpret `C-h` as backspace. Backspace is bounded to `C-h` and if you press backspace it will send `C-h` which means delete one character to the left. The same thing also happens with `C-m` and `Enter` or `C-i` and `Tab`. If someone finds a way to bound `Backspace` to some other thing other than `C-h` please mention me.
