### ISSUE TITLE
Can't move out of Vim, TmuxPaneCurrentCommand gives 'open terminal failed: not a terminal'

### ISSUE THREAD

**Issue by jackel119** [christoomey/vim-tmux-navigator#183] opened 2017-07-13 17:32 UTC
On tmux 2.5, running in Gnome-terminal (as well as Guake and tilix), copied the snippet into the tmux config (though I've changed the shortcut to Alt-Arrow keys). Moving from a standard tmux terminal into vim is fine, but moving out doesn't happen. On using :TmuxNavigateLeft (and right, up and down), nothing happens. Running :TmuxPaneCurrentCommand gives 'open terminal failed: not a terminal'.

Running on Arch Linux (up to date).

**Comment by jackel119** [comment] 2017-07-13 17:44
```
Entering Debug mode.  Type "cont" to continue.
cmd: TmuxPaneCurrentCommand
>
cmd: call s:TmuxPaneCurrentCommand()
>
function <SNR>32_TmuxPaneCurrentCommand
line 1: echo s:TmuxCommand("display-message -p '#{pane_current_command}'")
>
function <SNR>32_TmuxPaneCurrentCommand[1]..<SNR>32_TmuxCommand
line 1: let cmd = s:TmuxOrTmateExecutable() . ' -S ' . s:TmuxSocket() . ' ' . a:args
>
function <SNR>32_TmuxPaneCurrentCommand[1]..<SNR>32_TmuxCommand[1]..<SNR>32_TmuxOrTmateExecutable
line 1: return (match($TMUX, 'tmate') != -1 ? 'tmate' : 'tmux')
>
function <SNR>32_TmuxPaneCurrentCommand[1]..<SNR>32_TmuxCommand[1]..<SNR>32_TmuxOrTmateExecutable
line 1: End of function
>
function <SNR>32_TmuxPaneCurrentCommand[1]..<SNR>32_TmuxCommand[1]..<SNR>32_TmuxSocket
line 2: return split($TMUX, ',')[0]
>
function <SNR>32_TmuxPaneCurrentCommand[1]..<SNR>32_TmuxCommand[1]..<SNR>32_TmuxSocket
line 2: End of function
>
function <SNR>32_TmuxPaneCurrentCommand[1]..<SNR>32_TmuxCommand
line 2: return system(cmd)
>
function <SNR>32_TmuxPaneCurrentCommand[1]..<SNR>32_TmuxCommand
line 2: End of function
>
open terminal failed: not a terminal
function <SNR>32_TmuxPaneCurrentCommand
line 1: End of function
```

and 

```
ps -o state= -o comm= -t '$TMUX_PANE'
error:TTY could not be found
```

**Comment by christoomey** [comment] 2017-07-13 18:26
The `TmuxPaneCurrentCommand` debug helper is unfortunately out of date, but could you try the following and share the output:

``` sh
# run this in the tmux command prompt, which you can start with `prefix-:`
run-shell "tmux display-message -p '#{pane_tty}' | xargs ps -o state= -o comm= -t"
```

The pane should temporarily be taken over by the process tree listing. If possible, can you try while the current pane is running vim, as well as with the current pane as a shell session?

**Comment by jackel119** [comment] 2017-07-13 18:33
My apologies, just realized I forgot to mention I'm using neovim and not vim.
In neovim, running the command gives me:
```
S fish
S nvim
```

In just a shell, it gives me only S fish.

**Comment by christoomey** [comment] 2017-07-13 18:41
Hmm, that looks fine to me. The pattern match has logic to support `nvim` in place of `vim` as the process name, so no worries there.

Just to make sure we've checked the more obvious bits first, you've configured both tmux and [the vim side](https://github.com/christoomey/vim-tmux-navigator#vim-1) of the keybindings to support your use of the alt keys, correct?

**Comment by jackel119** [comment] 2017-07-13 18:45
Yeah, I have - but the problem isn't the key bindings, when I enter :TmuxNavigateLeft (or the other navigate-somethings) into neovim, nothing happens.

**Comment by christoomey** [comment] 2017-07-13 22:05
Thanks for clarifying that. Always good to double check the basics.

When you say 

> when I enter :TmuxNavigateLeft (or the other navigate-somethings) into neovim, nothing happens.

Can you clarify a bit? Specifically, are you able to navigate within Vim, but not put to tmux, or do the TmuxNavigate* commands do nothing regardless of which Vim pane is active?

**Comment by jackel119** [comment] 2017-07-13 22:16
:TmuxNavigate* works just fine within Vim splits, both up/down and left/right - just moving to other Tmux panes that doesn't work.

Also it seems Alt-Arrow keybinds aren't working, but that's likely because I've messed around A LOT with my terminal/tmux/vim settings so I should be able to fix that on my own later.

**Comment by christoomey** [comment] 2017-07-13 23:33
Interesting. Based on what you're describing, it sounds like the issues is when the Vim plugin calls back out to tmux to try to navigate.

Reading back through your comments, this might be due to the `$TMUX-PANE` variable not being set in your shell. Can you check on this by running `:echo $TMUX_PANE` in vim, and `echo $TMUX_PANE` in a a shell? You should see something like: `%28`.

You can also try running the navigate command directly by running the following in vim. `:echo system("tmux select-pane -t $TMUX_PANE -R")`. You should see no output (if you do, please share), but the tmux pane should change.

**Comment by jackel119** [comment] 2017-07-14 13:34
```echo $TMUX_PANE``` gives ```%4``` or another number depending on what terminal window or tmux pane. ```:echo $TMUX_PANE``` gives the same thing in a vim panel (also the same number as when I do it in the shell of the same pane).

```:echo system("tmux select-pane -t $TMUX_PANE -R")``` inside vim gives me ```open terminal failed: not a terminal ``.

**Comment by christoomey** [comment] 2017-07-14 14:27
Hi @jackel119, it sounds like the `open terminal failed: not a terminal` error is the source of the problem. Keybindings and the `$TMUX_PANE` env var all seem to be working fine, so I don't think there is any issue with the plugin / configuration, unfortunately.

I did a quick google of `open terminal failed: not a terminal` and there are a handful of results, but I wasn't able to figure anything out from them from my side. Unfortunately I think you'll have to sort that out (I'd recommend looking into your terminal as well as shell, and how terminal + tmux + shell + vim are all interacting) and I can't offer too much more help.

I'm going to close this now as I believe the issue is outside the scope of this plugin, but please feel free to comment or re-open if you think I missed anything. Also, please do share if you're able to resolve this, in the event that others run into this in the future.

**Closed by christoomey** 2017-07-14 14:27 UTC

**Comment by jackel119** [comment] 2017-07-14 14:31
Was just tinkering around with some other plugins and came to this conclusion myself - my apologies, I should have tested around this a bit more before posting a bug report. Thanks for your time.

**Comment by jackel119** [comment] 2017-07-14 15:30
Hi @christoomey 
Another plugin that kind of broke during my move to neovim was Syntastic - the helptags and everything worked but there was no syntax checking, after some further testing I found the common problem:

It turns out that running ```:echo system()``` within neovim through the fish shell doesn't work - I'm a little bit surprised as of why that is, considering that Syntastic worked just fine on normal Vim (on fish as well). Not sure if that's because neovim is lagging behind Vim in this aspect or something behind the scenes broke when I was tinkering around.

Anyways, the fix is merely telling Vim/Neovim to use a bash shell by adding this line to .vimrc:
```set shell=/bin/bash```
