### ISSUE TITLE
Jump between tmux windows

### ISSUE THREAD

**Issue by mxstbr** [christoomey/vim-tmux-navigator#184] opened 2017-09-04 09:57 UTC
I'd love to be able to go `<S-C-h/l>` to switch between tmux windows. I've added this to my `.tmux.conf`:

```tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

bind-key -n C-S-h previous-window
bind-key -n C-S-l next-window

run '~/.tmux/plugins/tpm/tpm'
```

But it doesn't seem to work. Any ideas what I'm doing wrong?

**Comment by christoomey** [comment] 2017-09-05 15:20
Hi @mxstbr, I don't believe tmux supports `C-S-h` or any similar variants at all, unfortunately. You can test this by trying to map `C-S-h` to `display-message "hello"`. 

```
tmux bind-key -n C-S-h display-message "hello"
```

I think this might actually be limited at a higher level (terminal or shell) not distinguishing between `C-h` and `C-S-h`.

As an aside, if you do end up installing with an alternate keybinding from the default set, unfortunately you won't be able to us the TPM installation as it hard codes to the default key bindings. The default installation method of copying in the tmux snippet should work for you, assuming you're using support key bindings.

Hope that helps! I'm going to close this now as I don't believe the issue is specific to this project, but please feel free to comment or re-open if you think I missed anything.

**Closed by christoomey** 2017-09-05 15:20 UTC

**Comment by mxstbr** [comment] 2017-09-05 16:00
Oh that makes total sense, I was so confused why that wasn't working I didn't even think of the possibility that it's a tmux limitation!

Thank you so much for this clear explanation, even though it has absolutely nothing to do with your project. I sincerely appreciate it. Also, while I'm here, thank you for making `vim-tmux-navigator`, it's working absolutely great for me and is making me 100x faster!

Have a great day!
