### ISSUE TITLE
MacOS + Crowdstrike issue with ps is causing lost input characters and hanging

### ISSUE THREAD

**Issue by nilbus** [christoomey/vim-tmux-navigator#417] opened 2024-11-21 21:17 UTC
This is not an issue with vim-tmux-navigator, but I wanted to document and make you aware of the issue I ran into today.

I've been using vim-tmux-navigator successfully for ages, but today `ps -t <tty>` decided to go crazy on my MacOS 14.6.1 machine today, as [documented here](https://apple.stackexchange.com/questions/476899/running-ps-t-dev-tty-started-causing-the-specified-terminal-to-stop-receiv). Specifically, whenever I hit any of the navigation keys in tmux anywhere (even not in vim), the terminal started dropping most of the keystrokes, causing me to need to repeat a key many times to get it through. Furthermore, if I did a tmux `:kill-window` on it instead of (tediously) exiting normally, other things in the system started hanging in a way that could not be killed with ^C or stopped with ^Z.

The root cause is vim-tmux-navigator's (valid) use of `ps -t <tty>` here in .tmux.conf:

```bash
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | \
grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
```

Running `ps` without `-t` continues to work just fine, so I replaced vim detection with this, which is only marginally less performant because it needs to generate and grep through more lines of processes:

```bash
is_vim="ps -o tty= -o state= -o comm= | \
grep -iqE '^#{s|/dev/||:pane_tty} +[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
```

If others hit this same issue, you might consider updating the suggested and bundled .tmux.conf `is_vim` detection to use this same approach.

Cheers for making a great plugin! 🎉

**Comment by jzw** [comment] 2024-11-22 17:25
@nilbus just wanted to say thanks for this. I was dead in the water all day yesterday trying to get to the bottom of this. Your suggested change works like a charm 👍

**Comment by mathieu-lemay** [comment] 2024-11-23 16:01
@nilbus @jzw Do you have Crowdstrike Falcon running on your macs? I'm facing the same issue and I noticed that `com.crowdstrike.falcon.Agent` opens a new file descriptor on the tty specified by `ps -t ...`, for every invocatoin of `ps -t`.

That would explain both the fact that it started two days ago even if there were no changes to the `ps` command, and also why the keystrokes are randomly lost and the problem just gets worse and worse over time

**Comment by jzw** [comment] 2024-11-23 17:24
@mathieu-lemay yep I have the crowdstrike agent running on my machine. Great find!

**Comment by iheanyi** [comment] 2024-11-23 17:48
Oh man, this is a great find. I was wondering why this randomly started this week when my computer has been fine otherwise. I thought I was going insane.

**Comment by nilbus** [comment] 2024-11-26 17:10
No Crowdstrike here. I do have similar daemons running on this work laptop that might be interfering similarly. 🤔

**Comment by nilbus** [comment] 2024-11-27 18:51
Correction: I _do_ have Crowdstrike installed. That's everyone reporting in so far. Seems like we should reach out to Crowdstrike.

**Comment by nilbus** [comment] 2024-11-27 20:46
We're sending this summary to Crowdstrike Support

The Crowdstrike agent recently started interacting poorly with MacOS `ps -t <tty>`, causing processes to hang and developers to be unable to open new terminals until rebooting or force-killing the Crowdstrike agent. This has caused days of productivity loss while we searched for the cause. Beyond our organization, all others [reporting this problem here](https://github.com/christoomey/vim-tmux-navigator/issues/417) are also Crowdstrike users.

Technical details:
1. Running `ps -t $(tty)` ([used internally by many tools](https://github.com/search?q=/%5Cb(?-i)ps+-t%5Cb.*?(pts%7Ctty)/&type=code)) causes Crowdstrike Agent to start consuming inputs from the specified terminal/tty such that most keypresses do not get sent to the shell. An affected terminal must be exited normally (`exit` or Ctrl+D) in order to not risk causing system-wide hanging.
2. Killing an affected terminal (e.g. by closing the tab in Terminal or iTerm apps, a natural reaction to its misbehaving) after typing in it (presumably thus allowing Crowdstrike to read characters from the tty) is likely to cause other process-related actions to hang. Running `ps -t $(tty)` and killing the affected terminal may need to be repeated to 1–4+ times to trigger. When this occurs:
    1. `ps` (e.g. `ps -ef`, `ps aux`) will hang while outputting processes. (You can run this in a loop with `while true; do ps; date; sleep 1; done` in a separate terminal to easily see when you’ve triggered the issue.)
    2. Anyone using homebrew can no longer open a new terminal window/tab, because this standard homebrew shell configuration line `BREW_PREFIX=`brew --prefix`` (e.g. in `.bashrc`) hangs and cannot be killed with Ctrl+C or Ctrl+Z.
3. Force-killing to restart the Crowdstrike agent (`ps -e -o pid= -o comm= | grep crowdstrike | awk '{print $1}' | xargs sudo kill -9`) restores normal behavior: All hanging process resume, and keystrokes are no longer swallowed in an affected terminal.

**Comment by nilbus** [comment] 2024-11-27 22:23
@sliminality re: c97c638, I don't think that we should make this the default for everyone. It is less performant, and I am noticing it. For example, when I vim-tmux-navigate down from vim to a tmux pane with a shell, I find that now some of my keystrokes intended for the shell are getting in to vim before it actually switches focus to the shell pane. It's not awful and is way better than the previous behavior, but I wouldn't want to put this delay on most people who aren't affected by the Crowdstrike bug. Hopefully they come out with a fix soon! 🤞

**Comment by sliminality** [comment] 2024-11-28 17:23
@nilbus ah, to be clear I'm not suggesting this ought to be the default! I was simply making a temporary change to my own local config, just to work around the issue for now. If I inadvertently opened a PR or pushed to the wrong branch that's my mistake.

**Comment by nilbus** [comment] 2024-11-29 12:55
@sliminality oops, sorry! That's just me not realizing what repo that was in. I saw `master` and stopped paying attention. 😅

**Comment by christoomey** [comment] 2024-11-30 17:01
Well this is certainly a wild ride! I'm going to close this issue as I don't believe there are any issues with the plugin itself here, but please continue to capture any relevant details here in hopes of aiding other folks who might bump into similar issues.

**Closed by christoomey** 2024-11-30 17:01 UTC

**Comment by jzw** [comment] 2024-12-05 16:10
> I was asked today by Crowdstrike to provide full diagnostics logs and a video demonstrating the issue. At least it seems they are looking at it.

Same here.

**Comment by mathieu-lemay** [comment] 2024-12-09 20:20
I got feedback from them. They are not able to open the tgz created by their own diagnostic tool. I was given a screenshot of the file not opening correctly with "Archive Utility" on macOS. Then they redirected me to this current issue.

Never mind that the issue is 100% reproducible and trivially so.

It won't be an easy ride.

**Comment by mathieu-lemay** [comment] 2024-12-10 20:20
I just had a call with my IT team and we decided to try different versions of Falcon. They use a policy of using latest -1 so I was on version `7.19.18810`. We first downgraded to `7.18.18071` and the problem was gone. We then updated to the latest version, `7.20.18904`, and the problem is also not present. Looks like 7.19 introduced it and it was fixed in 7.20.

**Comment by nilbus** [comment] 2024-12-10 22:51
> Edit: I wrongfully stated that 7.20 fixed it but it didn't. The issue is
> still present
>
Thank you for this update.

**Comment by askoufis** [comment] 2025-03-19 22:35
For anyone that uses the same tmux config on both Linux and MacOS, you may need to go one step further and conditionally set `is_vim` depending on your OS.

I found that `ps -o tty= -o state= -o comm=` when run in a TMUX pane with `nvim` open would result in process entries with a `?` instead of an actually TTY name. I'm not sure why this happens, but it results in the regex failing to match anything, so the pane switching hotkeys always think they're inside tmux, and never `nvim`.

Here's [the commit](https://github.com/askoufis/dotfiles/commit/81a161ef76b93b353eb99377102f43cd48c8ba3e) in case anyone runs into this issue.

**Comment by nabellows** [comment] 2025-03-27 01:00
I am curious why ps is needed at all? I was finding that it was still a performance bottleneck and simplified my config to: 
```
not_tmux='#{m/r:^(n?vim|fzf)$,#{pane_current_command}}'

bind-key -n 'C-h' if-shell -F "$not_tmux" 'send-keys' 'select-pane -L'
bind-key -n 'C-j' if-shell -F "$not_tmux" 'send-keys' 'select-pane -D'
bind-key -n 'C-k' if-shell -F "$not_tmux" 'send-keys' 'select-pane -U'
bind-key -n 'C-l' if-shell -F "$not_tmux" 'send-keys' 'select-pane -R'
```

Do let me know if there are issues with this approach, but it seems to be the tmux-native way?

**Comment by askoufis** [comment] 2025-06-15 09:58
> I am curious why ps is needed at all? I was finding that it was still a performance bottleneck and simplified my config to:

@nabellows Your simpler version is actually perfect for me. I'm not particularly concerned about  navigation when piping to `fzf` (for example), at least as far as my personal workflow is concerned. Your simple regex against `pane_current_command` does the job, and is very fast, which I appreciate greatly on my Crowdstrike-hampered Macbook pro.
