### ISSUE TITLE
Vim suspending after switching to another pane

### ISSUE THREAD

**Issue by Nimdis** [christoomey/vim-tmux-navigator#97] opened 2015-11-29 14:00 UTC
Hello. I am stuck with a problem
When I leave vim and go to the next tmux's pane, vim is suspending.

Vim 7.4
Tmux 2.0
Ubuntu 15.04

Note: I use the plugin through ssh

**Comment by christoomey** [comment] 2015-11-30 00:06
Hello @Nimdis, sorry to hear about the trouble. Unfortunately I've not run into or heard of this particular issue, but hopefully we can sort it out.

To be clear, are both Vim and tmux running on the remote server, or is tmux running locally and wrapping SSH?

Assuming the former, I'd take a look at [the commands that run when navigating from Vim to tmux](https://github.com/christoomey/vim-tmux-navigator/blob/999d252134d7bcd5e488a611f795c6500c198d92/plugin/tmux_navigator.vim#L62-L75). You might want to try them on their own to see if you can reproduce.

Hope that helps move you in the right direction. Let me know if you get any more info.

**Comment by blueyed** [comment] 2016-01-11 21:46
@Nimdis 
How is it suspending?  Similar to / like when pressing <kbd>Ctrl-Z</kbd>?

**Comment by blittle** [comment] 2016-03-08 19:44
I am having the same problem, I am running tmux locally (not through ssh) and when from within vim I switch to another tmux pane, vim gets suspended. I can switch back to the original pane and restore vim with `fg`

![image](https://cloud.githubusercontent.com/assets/1566869/13613945/6db131a8-e52b-11e5-9736-677abc4b03e9.png)

**Comment by blittle** [comment] 2016-03-08 20:21
This is the problem https://github.com/christoomey/vim-tmux-navigator/blob/master/plugin/tmux_navigator.vim#L80

When I change tha tline to be `call s:TmuxCommand(args)` it works properly.

**Comment by StevenCooks** [comment] 2016-03-14 03:55
@blittle Cool, your suggestion works, thanks!
More context:  
When I was using bash,  everything worked well. After I changed to zsh(yadr), I came across the same issue here.  Maybe there is a conflict.

**Comment by blueyed** [comment] 2016-03-14 23:58
You could try using the `debug` prefix with calls from the vim script and then see where the suspension happens.

**Comment by jz1371** [comment] 2016-05-02 06:17
Hi, guys! I came across the same problem and this problem also happened to other vim plugins, so it looks like vim-tmux-navigator is innocent. (BTW, cool plugin, thanks!)

If you're using zsh,  try adding this line in your ~/.vimrc:

`set shell=/bin/zsh\ -l`

See Bailey Parker's comment (at the bottom) at http://apple.stackexchange.com/questions/199520/suspended-tty-output-when-launching-editors-like-vim-vi-emacs-or-nano/199537#199537?newreg=961a30cb9c254c1082b853d6e126fe9a

**Comment by EugeneKey** [comment] 2016-12-06 17:06
I faced the same problem when using YADR on Ubuntu.
The problem is not in the plugin, but in Vim configuration.

You must specify the correct shell in ~/.vim/settings/path.vim

`set shell=/usr/bin/zsh\ -l`
instead `set shell=bash\ -i `

**Comment by blueyed** [comment] 2016-12-06 17:46
Try `stty -tostop` (via http://www.linusakesson.net/programming/tty/ at the bottom) - probably before starting Vim inside of tmux or a new tmux server in general.
You might change `stty` (or shell options in this regard) in your shell config, which is only meant to be done for interactive mode.

**Comment by GameKyuubi** [comment] 2017-08-15 09:21
I've got the same problem.  Only plugin running is vim-tmux-navigator.  When I do Ctrl-h/j/k/l/ vim suspends, and then when I type a key the command "logout" gets appended and run in the command prompt.  So if I do Ctrl-k, vim gets stopped, and I'm dropped to bash prompt, then I type 'f' to type 'fg' to get back into vim, but 'flogout' gets entered into the terminal and run, which produces an error, and then I can type 'fg' to get back into vim.  This is Ubuntu 16.04.  Vim config:

`syntax on
set tabstop=2
set shiftwidth=2
set expandtab
set noshowmode
set shellcmdflag=-ic
set number
set foldlevel=2
set nofoldenable
set foldmethod=indent
set foldnestmax=10
set laststatus=2

filetype plugin on
set omnifunc=syntaxcomplete#Complete

" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugged')
" Plug 'tpope/vim-commentary'
" Plug 'majutsushi/tagbar'
" Plug 'scrooloose/nerdtree'
Plug 'christoomey/vim-tmux-navigator'
" Plug 'itchyny/lightline.vim'
" Plug 'ap/vim-buftabline'
" Plug 'junegunn/rainbow_parentheses.vim'
" Plug 'airblade/vim-gitgutter'
" Plug 'mxw/vim-jsx'
" Plug 'pangloss/vim-javascript'
call plug#end()

let g:jsx_ext_required = 0 

" \ev to edit .vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" \sv to source .vimrc
nnoremap <leader>sv :source $MYVIMRC<cr>

" Method navigation workaround for modern syntax
map [[ ?{<CR>w99[{
map ][ /}<CR>b99]}
map ]] j0[[%/{<CR>
map [] k$][%?}<CR>

nnoremap <C-t> :TagbarToggle<CR>
nnoremap <C-n> :NERDTreeToggle<CR>

" let g:lightline = {
"       \ 'colorscheme': 'solarized',
"       \ }
`

.tmux.conf :
`# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

set -g default-terminal "screen-256color"
set-window-option -g mode-keys vi
`

**Comment by blueyed** [comment] 2017-08-15 12:34
Did you try if `stty -tostop` fixes it?
What does `:echo &shell` give you?
Is there any output if you start a new shell?

@blittle / @stevencooks 
Re https://github.com/christoomey/vim-tmux-navigator/issues/97#issuecomment-193952086 - that call is/was silent already?!
https://github.com/christoomey/vim-tmux-navigator/blob/1298b71/plugin/tmux_navigator.vim#L80
Can you provide a diff for what you suggest?

It sounds like this gets triggered for people (mostly/only) with Zsh, where probably there is some output with a non-interactive shell, e.g. caused by something in zshenv that should be in zshrc?!

**Comment by blueyed** [comment] 2017-08-15 14:22
See also https://apple.stackexchange.com/a/199522/27911.

**Comment by blueyed** [comment] 2017-08-15 14:26
Does `:call system('true')` cause the same behavior?

FWIW, I could not reproduce it using `:let &shellcmdflag='-c -i'` - also using Zsh myself.

**Comment by GameKyuubi** [comment] 2017-08-26 11:04
> It sounds like this gets triggered for people (mostly/only) with Zsh, where probably there is some output with a non-interactive shell, e.g. caused by something in zshenv that should be in zshrc?!

Sorry about the late reply, it's been a busy week.  I'm in bash.  `stty -tostop` didn't fix it.  It seems to happen when I try to leave a vim panel, but I swear it's happened other times too.

`:verbose set shell?` returns
```
  shell=/bin/bash
        Last set from ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/utility.vim
```

`:verbose set shellcmdflag?` returns
```
  shellcmdflag=-ic
        Last set from ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/utility.vim
```

**Comment by blueyed** [comment] 2017-08-26 18:52
@GameKyuubi 
The `-i` seems to cause it, which invokes an interactive shell (and also sources different rc files).

>> Is there any output if you start a new shell?

> Under what conditions? Just starting a new shell outputs nothing.

I suspect that using `-i` is the cause of some output (via something you do in your startup file(s)), which then suspends the command.

**Comment by christoomey** [comment] 2017-12-31 13:32
Reading back over this issue, it looks as though the issue is the `-i` shell flag set by some configurations and other plugins. I'm not sure we'll be able to resolve this in a sane way on our side, so I think we'll have to leave it at that. I'm going to close this now with that in mind, but please all feel free to comment or re-open should you think I missed something.

**Closed by christoomey** 2017-12-31 13:32 UTC
Labels: bug

**Comment by sdondley** [comment] 2019-03-31 19:36
Just adding a little more information on this issue. I got this in my .vimrc in on mac:

`set shellcmdflag=-ic`

It works fine on a mac.

Copying this over to my Debian linux box caused it to crash when switching between panes. Guess I'll need to find another way to sneak bash aliases into vim on linux.

**Comment by sdondley** [comment] 2019-03-31 22:24
OK, got a workaround. Instead of setting  `shellcmdflag`, you can do this instead in your .vimrc:

set shell=/bin/bash\ --login
