### ISSUE TITLE
Problems with ctrl-h in neovim

### ISSUE THREAD

**Issue by pwntester** [christoomey/vim-tmux-navigator#71] opened 2015-04-16 10:00 UTC
Hi, First of all, this is a great addition to my workfow, thanks!

I know, this is probably a problem with neovim, but control-h does not work there using standard configuration. Is there anything that can be done with any mapping settings?

Thanks
A

**Comment by christoomey** [comment] 2015-04-16 12:40
Hi @pwntester, glad you've found it useful!

I'm not a neovim user myself, but my guess is that the issue lies there. You can confirm that the mapping is configured properly by running:

``` vim
verbose nmap <C-h>
```

And it should mention tmux navigator.

Also, I think #61 is about the same issue and might contain a fix.

**Comment by pwntester** [comment] 2015-04-16 15:20
Thanks!
```
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
```
That worked for me, thanks!!!

**Comment by christoomey** [comment] 2015-04-16 15:23
Glad to hear it. Closing this now as your issue seems resolved, but please feel free to reopen or comment if needed.

**Comment by alexlafroscia** [comment] 2015-04-24 06:43
I'm seeing this issue too, everything works except for `<C-H>` despite the fact that `:TmuxNavigatorLeft` is fine.

**Comment by domluna** [comment] 2015-06-04 19:16
I think might be a problem with the bash shell and the regex.

I had

```
set shell=/bin/bash
```

That shell was 3.2

I changed it to

```
set shell=/usr/local/bin/bash
```

This one is 4.3

and the issue seems to be gone.

**Comment by jondkinney** [comment] 2015-06-09 17:19
Pasting the fix @pwntester mentioned and using a brew based 4.3 version of bash seems to have fixed this issue for me for neovim when not run inside of tmux. But I still can't `C-h` in vim when using tmux. It'll navigate the tmux splits with `C-h` just fine, but when it gets to vim, then `C-h` is just a noop.

**Comment by LazerPanther** [comment] 2015-06-26 04:17
Was having the same issue with everything but *Ctrl+h* working in Neovim and Tmux.

>infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
>tic $TERM.ti

No idea what that snippet does, but after running it in zsh, *Ctrl+h* now works

**Comment by felixjung** [comment] 2015-07-30 12:44
Hm I can't run ``tic $TERM.ti`` to verify the fix. Otherwise I'm also having this problem. Using homebrew zsh.

**Comment by megalithic** [comment] 2015-08-25 02:06
also having the issue @felixjung / @christoomey.
osx 10.10.5
homebrew
tmux
zsh
neovim (terminal brew vim works fine)
i've tried with both xterm-256color and screen-256color

output of `verbose nmap <C-h>`:

```sh
<C-H>       * :TmuxNavigateLeft<CR>
Last set from ~/.nvimrc
```

**Comment by daveyarwood** [comment] 2015-10-09 18:41
I'm experiencing what I think may be a strange variation on this problem... for me, `<C-h>` is being captured by Neovim (in both normal and insert mode) and sending `<BS>`, despite the fact that it is mapped to `:TmuxNavigateLeft`.

`:verbose nmap <C-h>` produces the following:

```
n  <C-H>       * :TmuxNavigateLeft<CR>
        Last set from ~/.vim/bundle/vim-tmux-navigator/plugin/tmux_navigator.vim
```

`<C-h>` seems to work in Neovim, it's just sending `<BS>`, which I have mapped to `gg`, so it's putting my cursor at the top of the file I'm in. Which makes me suspect that something somewhere has mapped `<C-h>` to `<BS>` with `nmap` instead of `nnoremap`.

Using Vim instead of Neovim, there is no problem. Adding `nnoremap <C-h> :TmuxNavigateLeft<CR>` to my `~/.nvimrc` doesn't help.

**Comment by daveyarwood** [comment] 2015-10-09 18:42
@megalithic Do you recall what exactly from that Neovim issue solved it for you?

**Comment by daveyarwood** [comment] 2015-10-09 19:01
> Thanks!
>
> ```
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
```
> That worked for me, thanks!!!

+1 on this -- it worked for me. It sounds like they are working on a fix for this in Neovim, something about upgrading the version of libtermkey that they use.

**Comment by megalithic** [comment] 2015-10-09 19:03
@daveyarwood SUPER late responding to you; sorry about that. yep, your `tic` block did the trick for me.

**Comment by hhsnopek** [comment] 2015-10-16 00:03
be sure to run:
```
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
```
within your HOME directory

**Comment by christoomey** [comment] 2015-10-24 23:40
@geoffharcourt I think I remember you sharing some comments around this recently. Can you shed any light on this for me (I'm not using neovim so not familiar with the issue).

Is there a clean solution we can recommend?

**Comment by geoffharcourt** [comment] 2015-10-25 13:11
I have `<BS>` in normal mode mapped to `:TmuxNavigateLeft<cr>` like [this](https://github.com/geoffharcourt/dotfiles/blob/master/vimrc.local#L24) in my dotfiles. This solution fixes Vim/Tmux navigation, but should just be a bandaid until the Neovim team resolves their terminal keybinding issues. The issue has been open for months and doesn't seem to close to a consensus resolution yet.

There are some other solutions available, but they involve updating with `tic`, and I don't think we should be asking end-users to make those changes lightly.

**Comment by mcmire** [comment] 2015-11-19 22:25
I just had an issue with this too. Here's what solved it for me:

* You have to fix Neovim somehow so that it doesn't override `<C-h>`. Updating `tic` as in [this comment](https://github.com/neovim/neovim/issues/2048#issuecomment-78045837) worked for me, but treating `<C-h>` as `<BS>` and mapping `TmuxNavigateLeft` to it would work too (hammer vs. scalpel).
* Make sure you're using the tmux mappings described in the [README](https://github.com/christoomey/vim-tmux-navigator#tmux). Originally I didn't do this because I was having some sort of issues with it, but everything seems to work great now.

**Comment by dckesler** [comment] 2016-01-20 18:24
If anyone has this problem with iTerm2 I found a solution [here](https://github.com/neovim/neovim/issues/2048).
Specifically badeip says to go to
iTerm -> Preferences -> Keys
Add a new Global Shortcut Key. (Press +)
Press Ctrl+h as Keyboard Shortcut
Choose Send Escape Sequence as Action
Type [104;5u for Esc+

**Comment by thewatts** [comment] 2016-02-15 20:24
@dckesler your solution worked for me :+1: !!

**Comment by thewatts** [comment] 2016-02-15 20:52
I noticed that when trying `control-h` in prezto, it was enabling my vim bindings.

Removed that plugin and now `4;5u` is output whenever using `control-h` in a tmux split.

**Comment by thewatts** [comment] 2016-02-15 21:00
So, something in combination with removing [this line in my `.zshrc` file](https://github.com/thewatts/dotfiles/blob/master/.zshrc#L48), and [this suggestion](https://github.com/neovim/neovim/issues/2048#issuecomment-78045837) fixed things.

Hate that I don't know the exact ticket to get it working... will have to see if I can reproduce later.

**Comment by geoffharcourt** [comment] 2016-02-16 13:29
@thewatts it appears you have an involved enough setup with Prezto, etc. that you'd be best off bisecting your configuration to find the offending portions.

1. Start with the most vanilla configuration possible (comment out everything in your `tmux.conf` other than this plugin's required lines, disable any zsh tools like Prezto / oh-my-zsh / tmux plugin manager, etc.)
2. Demonstrate that the vim-tmux-navigator works in your terminal
3. Uncomment half of what's commented, test that it works
4. Roll back if the uncommenting breaks the plugin and then try uncommenting fewer lines.

One of the pitfalls of having a very involved setup (I say this as someone who runs a very large number of Vim plugins) is that debugging these problems takes a little time due to interaction across all the different things you've got in the mix.

**Comment by PaBLoX-CL** [comment] 2016-03-26 21:01
The solucition above about monkey-patching the terminfo, has to be run all the time?

**Comment by geoffharcourt** [comment] 2016-03-28 14:47
@christoomey this is actually a Neovim issue with a long history and not anything specific to the plugin. I think we should close this issue out, folks can get involved in the discussion on the Neovim repo.

**Comment by christoomey** [comment] 2016-03-29 16:05
@geoffharcourt I totally agree. Do you think you could write up a brief summary for the [troubleshooting section](https://github.com/christoomey/vim-tmux-navigator#troubleshooting) of the README w/ link to this issue and or the neovim issue? Assuming it's not too much to ask, I've just added you as a collaborator so feel free to open as PR, or if you'd prefer, you can add the summary here and I'll add then we can close this issue.

**Comment by zackhsi** [comment] 2016-04-06 22:05
This fixes it perfectly for me:

```viml
if has('nvim')
    nmap <BS> :<C-u>TmuxNavigateLeft<CR>
else
    nmap <C-h> <C-w>h
endif
```

**Comment by bernastoc** [comment] 2016-04-08 17:24
Even without neovim/vim, I cannot jump to the left pane with ctrl-h with the provided modifications to .tmux.conf. This isn't solely a neovim issue and/or there are multiple issues.

**Comment by geoffharcourt** [comment] 2016-04-29 14:08
@christoomey so sorry this took so long to get to, I haven't had much investment time lately. I've suggested https://github.com/christoomey/vim-tmux-navigator/pull/122 to update the documentation and link to solutions.

**Closed** 2016-04-29 15:49 UTC
Labels: wontfix

**Comment by doomzhou** [comment] 2016-06-20 03:26
I have the issue too when i switch [termite](https://github.com/thestinger/termite) to [xterm](https://en.wikipedia.org/wiki/Xterm).

so i adjust configure in .zshrc 

in origin env

    tmux
    zsh
    termite
    vim

`export TERM='screen' ` is fine!

my new env

    tmux
    zsh
    xterm
    vim 

`export TERM='screen-256color'` is worked for me

**Comment by yifanchen** [comment] 2017-07-21 23:08
Has issue been fixed in 0.2.0?

**Comment by kcajf** [comment] 2019-12-05 20:38
@bernastoc did you ever get this working ? I'm in the same situtation - not a neovim issue, but just tmux - and also using MobaXTerm

**Comment by bernastoc** [comment] 2019-12-05 22:51
> @bernastoc did you ever get this working ? I'm in the same situtation - not a neovim issue, but just tmux - and also using MobaXTerm

The second paragraph in my post describes what I did ;)

**Comment by kcajf** [comment] 2019-12-05 23:43
Ah, somehow missed that. Thanks!
