### ISSUE TITLE
Wrap around destination is potentially bugged

### ISSUE THREAD

**Issue by Falkgaard** [christoomey/vim-tmux-navigator#249] opened 2020-01-27 22:25 UTC
Hi, I love the plugin!

However, one thing I've noticed is that when it wraps around into Vim, it jumps into the last active vim pane and not the one that is opposite of the side that you wrapped around from. Is this a bug or intended behaviour..?

Keep up the great work!
-F

**Comment by christoomey** [comment] 2020-01-28 14:21
Hi @Falkgaard, the current behavior is working essentially as intended as any other version would require adding a good bit more complexity to the project, and my primary goal with this thing has been to keep it stable, rather than add more features. You can see [some](https://github.com/christoomey/vim-tmux-navigator/pull/221) of [the](https://github.com/christoomey/vim-tmux-navigator/pull/237) previous [discussions](https://github.com/christoomey/vim-tmux-navigator/issues/70) on the topic to get a better sense of what has been considered.

I certainly wouldn't rule this out as something that might be updated in the future, but for now I'm not planning on any changes.

I'm going to close this issue now as I don't think there is any immediate action, but please feel free to comment or reopen if you think I missed anything.

**Closed by christoomey** 2020-01-28 14:21 UTC
